[package]
name = "xhidecursor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.23", features = ["derive"] }
ctrlc = "3.2.3"
x11oo = { version = "0.1.1", features = ["xfixes"] }
