[package]
name = "xhidecursor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.23", features = ["derive"] }
x11oo = { version = "0.2.3", features = ["xfixes"] }
signal-hook = "0.3.14"
